"use client";

import { useState } from 'react';
import Header from '@/components/header';
import Footer from '@/components/footer';
import SlideUp from '@/components/slide';
import { useScrollToHash } from '@/hooks/useScrollToHash';

export default function TermsPage() {
    useScrollToHash();

    return (
        <main className="min-h-screen bg-[#F9F9F9] text-gray-600 relative overflow-x-hidden">
            <Header />
            <div className="bg-[#F9F9F9] py-12 sm:py-20">
                <div className="max-w-7xl mx-auto px-4 sm:px-8">
                    <section className="px-4 py-8">
                        <SlideUp>
                        <h1 className="text-3xl sm:text-4xl font-bold mt-8 mb-10 text-center">Terms of Service</h1>
                        </SlideUp>
                        <p className="mb-10">Latest Update: This Terms of Service was last updated on: September 16, 2024</p>
                        <p className="mb-4">Welcome to Canopy Wave! As part of our commitment to you, we have drafted the following terms to support a smooth and vibrant user experience. It is important for you to read the Terms and Conditions carefully, as they contain important information and restrictions regarding your use of our services. These Terms are a binding agreement between us, Canopy Wave Inc. a Delaware Corporation (“Canopy Wave”, “us”, “we”, “Company), and You, whether you are an individual user, or a user on behalf of a company or team (“User”, “Customer”, “You”).</p>
                        <p className="mb-4">Whenever you want to use the Services that we provide at www.canopywave.com and related sites (the "Sites"), these Terms of Service, together with any supplemental terms, notices, and policies available at `https://canopywave.com/,` and/or any other binding document signed between the parties (the “Terms” or the “Agreement”) will apply to you.</p>
                        <p className="mb-4">YOUR CONTINUED ACCESS AND USE OF THE SERVICE ARE CONDITIONAL ON YOUR ACCEPTANCE OF AND CONTINUED COMPLIANCE WITH THE TERMS. By accessing or using the Service in any manner, including, but not limited to, visiting or browsing the Sites, registering an account, or contributing content or other materials to the Sites, you expressly understand, acknowledge and agree to be bound by these Terms. In addition to these Terms, our Privacy Policy governs how Canopy Wave collects, stores, and protects your information when you use the Services.</p>
                        <p className="mb-4">We may change or update the Terms from time to time. Changes will be effective 10 days following posting on the Site. You accept any changes by your continued use of the Services 10 days following such posting.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">USE OF OUR SERVICES</h2>
                        <p className="mb-4">When you create an account or use our Services, you are representing that the information you submit is truthful and accurate, your use of the Services does not violate any applicable law or regulation, and that you are of sufficient legal age or otherwise have the legal capacity to legally enter into these Terms. We reserve the right at any time to modify, suspend, or discontinue, either temporarily or permanently, the Services (in whole or in part) with or without notice. Canopy Wave is not liable to you or any third party for any modification, suspension, or discontinuation of the Services.</p>
                        <p className="mb-4">To ensure the security of our Services, we depend on you to maintain the confidentiality and security of any account credentials. Do not disclose or share your credentials with any third parties. You are solely responsible for any actions taken using your Accounts. Please notify us immediately in the event of any actual or suspected breach of security or unauthorized use of your Account.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">YOUR CONTENT</h2>
                        <p className="mb-4">You are solely responsible for the Content you post, host, or otherwise make available on our Sites. You represent and warrant that any Content you transmit through our Service is truthful, accurate, not misleading, and that you have the right to transmit such Content. Your Content must not be misleading; in violation of any laws, regulations, or these Terms; or infringe or misappropriate any rights of any other person or entity. Canopy Wave may but shall not be obligated to remove or edit any Content (including comments or reviews) in our sole discretion for any reason including Content in violation of our acceptable use policy.</p>
                        <p className="mb-4">While you own any Content you create, by posting or otherwise making Content available on our Sites you may be granting certain rights to Canopy Wave and other Users, including:</p>
                        <ul className="list-disc pl-5 mb-4">
                            <li>You grant Canopy Wave a worldwide, royalty-free, perpetual, sublicensable, right and license to use, display, publish, reproduce, distribute, or otherwise make available to others as permitted under these Terms and our Privacy Policy.</li>
                            <li>If you decide to set your Canopy Wave Demos as public, you grant each other User a perpetual, irrevocable, worldwide, royalty-free, non-exclusive license to use, download, display, publish, reproduce, distribute, and make derivative works of your Content through our Services and functionalities.</li>
                            <li>If you decide to set your Canopy Wave Demos as unlisted, we will not list your Canopy Wave Demo on our Demos Discovery Page and it will not be searchable on our site or by search engine. However, unlisted demos can be seen, used, and shared, by anyone with the link. By providing access to certain Users or Teams you are granting those Users or Teams a perpetual, irrevocable, worldwide, royalty-free, non-exclusive license to use, download, display, publish, reproduce, distribute, and make derivative works of your Content through our Services and functionalities.</li>
                        </ul>
                        <p className="mb-4">When Content contains notice of a reasonable and customary license, (such as an open source license) such Content is intended to remain under the terms of such license when further accessed, distributed, or used. Neither party is permitted to remove reference to any such license. Any Content you download, access, or use from us or another User, is at your own risk and subject to these Terms and/or the terms accompanying such Content.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">THIRD PARTY LINKS AND TOOLS</h2>
                        <p className="mb-4">Certain content, products, services, and tools available via our Service may include materials from third parties provided as a convenience for Users. Third-party links on this site may direct you to third-party websites not affiliated with Canopy Wave. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or any other materials, products, or services of third parties.</p>
                        <p className="mb-4">We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third party.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">INTELLECTUAL PROPERTY RIGHTS</h2>
                        <p className="mb-4">Canopy Wave retains ownership of all intellectual property rights related to the Sites, Products, and Services, including all improvements to such. All materials we produce, including the Sites, design, code, graphics, interfaces, trademarks, and logos shall remain our exclusive property. We do not authorize you to alter, reproduce, republish, or license any of our materials absent express written permission. Any rights not expressly granted herein are reserved and retained by us.</p>
                        <p className="mb-4">If you provide feedback relating to the use, operation, performance, or functionality of our Sites, Products, or Services (“Feedback”), you hereby grant Canopy Wave a perpetual, irrevocable, worldwide, royalty-free, and non-exclusive right and license to exploit and commercialize such Feedback for any purpose which shall be solely and exclusively owned by Canopy Wave. You are not entitled to any compensation or reimbursement for Feedback unless expressly agreed in writing.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">DMCA POLICY</h2>
                        <p className="mb-4">We comply with the Digital Millennium Copyright Act Policy (DMCA). If you believe that material located on or linked to our Sites violates your copyright, you are encouraged to notify us following the DMCA guidelines. To do so, please send an email to legal@canopywave.com with the Subject Line “DMCA Notice” with detailed and accurate information supporting your claim. </p>
                        <h2 className="text-sm font-bold mt-8 mb-4">TERMINATION</h2>
                        <p className="mb-4">You may decide to cancel or delete your Account at any time for any reason. Similarly, we reserve the right to suspend or terminate your access to unpaid Services anytime with or without cause, in our own discretion, and with or without notice. </p>
                        <p className="mb-4">Upon Termination or cancellation Canopy Wave may, without obligation to do so (unless otherwise required by applicable law), delete any of your Content or data in its possession including deleting all file systems, storage blocks, virtual machines, and any usage data associated with the account without liability; provided, however, Canopy Wave may maintain a copy of any information in accordance with Canopy Wave’s data retention practices and our Privacy Policy. Even after the termination of these Terms,  your User Account, or access to a Site, any User Content you have posted or submitted may remain on our Services indefinitely.</p>
                        <p className="mb-4">You agree that if your use of our Services is terminated under these Terms, you will not attempt to use that Service under any name, real or assumed, and further agree that if you violate this restriction after being terminated, you will indemnify and hold us harmless from any and all liability that we may incur. Your use of the Service after termination will be a violation of this section, which survives any termination.
                            The provisions of these Terms concerning the protection of intellectual property rights, prohibited use, user-submitted Content, disclaimers, limitations of liability, indemnity, and Disputes, as well as any other provisions that by their nature should survive, shall survive any such termination.
                        </p>
                        <h2 className="text-sm font-bold mt-8 mb-4">ERRORS AND OMISSIONS</h2>
                        <p className="mb-4">On occasion, information on our Service may contain errors, including, without limitation, typographical errors, inaccuracies, or omissions. Canopy Wave reserves the right to, at any time without prior notice, correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information on the Service is inaccurate (including after you have submitted your order). In the event that an item is listed at an incorrect price or with incorrect information due to an error in pricing or product information, Canopy Wave shall have the right, at our sole discretion, to refuse or cancel any orders placed for that item. </p>
                        <h2 className="text-sm font-bold mt-8 mb-4">DISCLAIMER OF WARRANTIES</h2>
                        <p className="mb-4">EXCEPT AS EXPRESSLY PROVIDED OTHERWISE, AND TO THE FULLEST EXTENT PERMITTED BY LAW,  THE SERVICES, INCLUDING, WITHOUT LIMITATION, ALL SERVICES, CONTENT, FUNCTIONS, AND MATERIALS, ARE PROVIDED “AS IS” AND “AS AVAILABLE”, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY FOR INFORMATION, DATA, DATA PROCESSING SERVICES, UPTIME OR UNINTERRUPTED ACCESS, ANY WARRANTIES CONCERNING THE AVAILABILITY, ACCURACY, USEFULNESS, OR CONTENT OF INFORMATION, ANY WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE, AND WE HEREBY DISCLAIM ANY AND ALL SUCH WARRANTIES, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SITE OR THE SERVICE, CONTENT, FUNCTIONS, OR MATERIALS CONTAINED THEREIN WILL BE TIMELY, SECURE, UNINTERRUPTED, OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED. WE MAKE NO WARRANTY THAT THE SITE WILL MEET USERS’ REQUIREMENTS. NO ADVICE, RESULTS, OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR THROUGH THE SITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. CANOPY WAVE ALSO ASSUMES NO RESPONSIBILITY, AND SHALL NOT BE LIABLE FOR, ANY DAMAGES TO, OR VIRUSES OR OTHER HARMFUL COMPONENTS THAT MAY INFECT OR HARM, YOUR COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT OF YOUR ACCESS TO, USE OF, OR BROWSING IN THE SITE OR YOUR DOWNLOADING OF ANY MATERIALS, DATA, TEXT, IMAGES, VIDEO, OR AUDIO FROM THE SITE. IF YOU ARE DISSATISFIED WITH THE SITE, YOUR SOLE REMEDY IS TO DISCONTINUE USING THE SITE.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">LIMITATION OF LIABILITY</h2>
                        <p className="mb-4">YOU ACKNOWLEDGE, BY YOUR USE OF THE SERVICES THAT CANOPY WAVE WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND RELATED TO YOUR USE OF OR INABILITY TO USE OUR SERVICES, INCLUDING WITHOUT LIMITATION, FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, COMPUTER VIRUS, OR NETWORK OR INTERNET FAILURE, OR INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, SPECIAL, COMPENSATORY OR CONSEQUENTIAL DAMAGES, LOST PROFITS AND/OR LOSS OF OR DAMAGE TO PROPERTY WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE STRICT LIABILITY OR ANY OTHER BASIS, EVEN IF CANOPY WAVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL CANOPY WAVE’S TOTAL LIABILITY FOR ANY CLAIMS RELATED TO THIS SERVICE EXCEED THE AMOUNT PAID FOR THE SERVICE OR PRODUCT PROVIDED.
                        BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, CANOPY WAVE, ITS AFFILIATES’, AGENTS’, LICENSORS’, AND SUPPLIERS’ DAMAGES IN SUCH JURISDICTIONS SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">INDEMNITY</h2>
                        <p className="mb-4">You are solely and fully responsible for your use of the Services. You agree to defend, indemnify and hold Canopy Wave and its directors, officers, employees, agents, or service providers harmless from any and all claims, liabilities, costs, and expenses, including reasonable attorneys’ fees, arising directly or indirectly out of or from (i) your breach of any provision of these Terms; (ii) your activities in connection with our Services; or (iii) the Content or other information you provide to us through the Services. Canopy Wave reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with Canopy Wave’s defense of such claim.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">MISCELLANEOUS</h2>
                        <p className="mb-4">Governing law and dispute resolution. These Terms and all matters regarding their interpretation and/or enforcement are governed by the Laws of the State of Delaware, excluding its choice of law rules. If a dispute or claim relating to these Terms arises, we each agree to make a reasonable and good-faith effort to agree on an out-of-court solution and to resolve the dispute. If no out-of-court settlement is reached, any related action, lawsuit, or proceeding must be brought and adjudicated exclusively by state or federal courts located in the State of Delaware, United States of America. Any claim, action, suit, or proceeding relating to these Terms must be brought by you within one year of the event that gave rise to the claim or such claim is hereby waived to the maximum extent permitted by law.</p>
                        <p className="mb-4">Assignment. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Canopy Wave without restriction.</p>
                        <p className="mb-4">Changes in law or regulation. If there is any change in law or regulation that would materially restrict or prohibit our ability to provide the unpaid Services pursuant to these Terms, we may suspend or cancel the unpaid Services, or otherwise amend these Terms.</p>
                        <p className="mb-4">Export Control and Sanctions. Any Service provided pursuant to these Terms may be subject to export control and sanctions laws of the U.S. and/or other applicable jurisdictions. Therefore, you may only access and use the Service in compliance with U.S. and other applicable export control and sanctions laws and regulations.</p>
                        <p className="mb-4">Entire Agreement. These Terms, together with our Privacy Policy, Hardware & Software Terms of Sale, Refund Policy, Acceptable Use Policy and Cloud Terms of Service, and any other legal notices published on the Service, shall constitute the entire agreement between you and us concerning the Service and supersedes all prior terms, agreements, discussions and writings regarding the Service.</p>
                        <p className="mb-4">Order of Precedence. In the event of a conflict between provisions arising out of any documents included in the Agreement, the order of precedence will be as follows, unless expressly stated otherwise: (i) the applicable Order Form if any; (ii) the applicable ISA or MSA; (iii) any other binding document signed between us; (iv) the Supplemental Terms; (v) these Terms of Service; (vi) all other documents or policies incorporated by reference in the Agreement.</p>
                        <p className="mb-4">Severability. If any provision of these Terms, by action of law or for any other reason, is held to be prohibited, invalid, void, or unenforceable in any relevant jurisdiction, such provision will be stricken, and the remaining provisions of these Terms will remain in full force and effect.</p>
                        <p className="mb-4">No Waiver. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term. Our failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.</p>
                        <h2 className="text-sm font-bold mt-8 mb-4">CONTACT US</h2>
                        <p className="mb-4">We welcome your questions and comments about these Terms. You may contact us by email at legal@canopywave.com, or by writing us at Canopy Wave, Inc. 2350 Mission College Blvd, Santa Clara, CA 95054.</p>
                    </section>
                </div>
            </div>
            <Footer />
        </main>
    );
}